[workspace]
members = [
    "p3", 
    "wf"
]

[workspace.dependencies]
winterfell = { version = "0.13.0", default-features = false, features = ["std"] }
core-utils = { version = "0.13", package = "winter-utils", default-features = false, features = ["std"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }

# Plonky3 dependencies
p3-air = { path = "../Plonky3/air" }
p3-baby-bear = { path = "../Plonky3/baby-bear" }
p3-challenger = { path = "../Plonky3/challenger" }
p3-commit = { path = "../Plonky3/commit" }
p3-dft = { path = "../Plonky3/dft" }
p3-field = { path = "../Plonky3/field" }
p3-fri = { path = "../Plonky3/fri" }
p3-interpolation = { path = "../Plonky3/interpolation" }
p3-matrix = { path = "../Plonky3/matrix" }
p3-merkle-tree = { path = "../Plonky3/merkle-tree" }
p3-poseidon2 = { path = "../Plonky3/poseidon2" }
p3-symmetric = { path = "../Plonky3/symmetric" }
p3-uni-stark = { path = "../Plonky3/uni-stark" }
p3-util = { path = "../Plonky3/util" }
rand = { version = "0.9", features = ["small_rng"] }

[patch.crates-io]
winterfell = { path = "../winterfell/winterfell" }
winter-utils = { path = "../winterfell/utils/core" }
